"""Authoritative v5 M1-M8 release audit.

Missing golden data or external resource measurements are failures, not skipped gates.
The report never converts unit-test success into production acceptance by itself.
"""
import argparse
import csv
import json
import os
import struct
import subprocess
import sys
import tempfile
import zlib
from pathlib import Path
from typing import Callable, Dict, Optional

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


def _fail(reason: str) -> Dict:
    return {"result": "FAIL", "reason": reason}


def _load(path: Optional[str], label: str):
    if not path:
        raise ValueError(f"缺 {label} 路径")
    target = Path(path).expanduser().resolve()
    if not target.is_file():
        raise ValueError(f"{label} 不存在: {target}")
    return json.loads(target.read_text(encoding="utf-8"))


def _score_pair(golden: Optional[str], pred: Optional[str], label: str,
                evaluator: Callable) -> Dict:
    try:
        return evaluator(_load(golden, f"{label} golden"), _load(pred, f"{label} pred"))
    except (OSError, ValueError, RuntimeError, json.JSONDecodeError) as exc:
        return _fail(str(exc))


def _score_generated(golden: Optional[str], label: str,
                     generator: Callable, evaluator: Callable) -> Dict:
    """Evaluate deterministic gates using predictions generated by current code."""
    try:
        cases = _load(golden, f"{label} golden")
        result = evaluator(cases, generator(cases))
        result["prediction_source"] = "generated-current-code"
        return result
    except (OSError, ValueError, RuntimeError, json.JSONDecodeError) as exc:
        return _fail(str(exc))


def _score_m1_current(golden: Optional[str], evaluator: Callable) -> Dict:
    """Regenerate M1 predictions from source paths embedded in the golden manifest."""
    from tools.predict_m1 import generate
    try:
        cases = _load(golden, "M1 golden")
        with tempfile.TemporaryDirectory(prefix="paperbrain-release-m1-") as td:
            predictions = generate(cases, str(Path(td, "pred.json")),
                                   str(Path(td, "runs")))
        result = evaluator(cases, predictions)
        result["prediction_source"] = "generated-current-code"
        return result
    except (OSError, ValueError, RuntimeError, json.JSONDecodeError) as exc:
        return _fail(str(exc))


def _unit_tests() -> Dict:
    proc = subprocess.run(
        [sys.executable, "-m", "unittest", "discover", "-s", "tests", "-v"],
        cwd=str(ROOT), text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        timeout=300, check=False)
    lines = [line for line in proc.stdout.splitlines() if line.strip()]
    return {"result": "PASS" if proc.returncode == 0 else "FAIL",
            "returncode": proc.returncode, "tail": lines[-8:]}


def _m2() -> Dict:
    from paperbrain.budget import check_budget
    three = check_budget({}, num_images=3)
    nine = check_budget({}, num_images=9)
    ok = three.ok and not nine.ok
    return {"result": "PASS" if ok else "FAIL", "three_images_ok": three.ok,
            "nine_images_ok": nine.ok, "nine_images_reasons": nine.reasons}


def _m4(thresholds: str, tests: Dict) -> Dict:
    from paperbrain.calibration import load_record
    target = Path(thresholds).expanduser().resolve()
    try:
        raw = json.loads(target.read_text(encoding="utf-8"))
        scorer = str(raw.get("scorer", ""))
    except Exception as exc:
        return _fail(f"阈值记录不可读: {exc}")
    calibrated = load_record(scorer, target)
    ok = tests["result"] == "PASS" and calibrated.get("verified") is True
    return {"result": "PASS" if ok else "FAIL", "tests": tests,
            "calibration_verified": bool(calibrated.get("verified")),
            "calibration_reason": calibrated.get("reason", ""), "scorer": scorer}


def _m6(path: Optional[str]) -> Dict:
    try:
        report = _load(path, "M6 report")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return _fail(str(exc))
    required = (report.get("papers") == 50 and report.get("distinct_sha256") == 50 and
                report.get("functional_ok") is True and report.get("resource_ok") is True and
                report.get("external_resource_evidence") is True and
                report.get("idempotent_artifacts") is True and report.get("result") == "PASS")
    return {"result": "PASS" if required else "FAIL", "report": report}


def _m8(path: Optional[str]) -> Dict:
    from tools.validate_output_quality import evaluate
    try:
        target = Path(path).expanduser().resolve() if path else None
        report = _load(path, "M8 output-quality report")
        return evaluate(report, base_dir=target.parent)
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        return _fail(str(exc))


def _png_privacy_probe() -> bool:
    from paperbrain.vision import strip_png_metadata

    def chunk(kind, data):
        return (struct.pack(">I", len(data)) + kind + data +
                struct.pack(">I", zlib.crc32(kind + data) & 0xffffffff))
    raw = (b"\x89PNG\r\n\x1a\n" +
           chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0)) +
           chunk(b"eXIf", b"private-camera-data") +
           chunk(b"IDAT", zlib.compress(b"\x00\x00\x00\x00\xff")) + chunk(b"IEND", b""))
    with tempfile.TemporaryDirectory() as td:
        path = Path(td, "probe.png")
        path.write_bytes(raw)
        removed = strip_png_metadata(str(path))
        cleaned = path.read_bytes()
    return "eXIf" in removed and b"private-camera-data" not in cleaned


def _ledger_privacy_probe() -> Dict:
    from paperbrain.batch import run_batch
    old = {key: os.environ.get(key) for key in
           ("PAPERBRAIN_TEST", "PAPERBRAIN_CLOUD_ALLOWED", "PAPERBRAIN_PROVIDER",
            "PAPERBRAIN_MEMORY_DB")}
    try:
        with tempfile.TemporaryDirectory() as td:
            os.environ.update({"PAPERBRAIN_TEST": "1", "PAPERBRAIN_CLOUD_ALLOWED": "0",
                               "PAPERBRAIN_PROVIDER": "off",
                               "PAPERBRAIN_MEMORY_DB": str(Path(td, "memory.sqlite"))})
            result = run_batch([{"path": str(ROOT / "demo" / "sample_paper.txt")}],
                               str(Path(td, "out")), task="outline", depth="fast",
                               use_llm=False, resume=False)
            ledger = Path(result["ledger"])
            with open(ledger, newline="", encoding="utf-8") as f:
                rows = list(csv.DictReader(f))
            headers = set(rows[0]) if rows else set()
            allowed = {"source_sha256", "run_signature", "text_tokens", "vision_tokens",
                       "total", "input_tokens", "output_tokens", "llm_calls", "cost"}
            content = ledger.read_text(encoding="utf-8")
            return {"ok": len(rows) == 1 and headers == allowed and
                    "sample_paper" not in content, "headers": sorted(headers)}
    finally:
        for key, value in old.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


def _m7() -> Dict:
    from paperbrain import config
    old_test = os.environ.get("PAPERBRAIN_TEST")
    old_cloud = os.environ.pop("PAPERBRAIN_CLOUD_ALLOWED", None)
    os.environ["PAPERBRAIN_TEST"] = "1"
    try:
        default_cloud_off = not config.cloud_allowed()
    finally:
        if old_cloud is not None:
            os.environ["PAPERBRAIN_CLOUD_ALLOWED"] = old_cloud
        if old_test is None:
            os.environ.pop("PAPERBRAIN_TEST", None)
        else:
            os.environ["PAPERBRAIN_TEST"] = old_test
    compose = (ROOT / "docker-compose.yml").read_text(encoding="utf-8")
    localhost_only = '"127.0.0.1:8000:8000"' in compose
    ledger = _ledger_privacy_probe()
    png = _png_privacy_probe()
    ok = default_cloud_off and localhost_only and ledger["ok"] and png
    return {"result": "PASS" if ok else "FAIL", "cloud_default_off": default_cloud_off,
            "localhost_binding": localhost_only, "privacy_ledger": ledger,
            "png_metadata_probe": png}


def evaluate_release(*, m1_golden=None, m1_pred=None, m3_golden=None, m3_pred=None,
                     m5_golden=None, m5_pred=None, m6_report=None,
                     output_quality_report=None,
                     thresholds: Optional[str] = None, run_tests: bool = True) -> Dict:
    from tools.score_m1 import evaluate as score_m1
    from tools.score_m3 import evaluate as score_m3
    from tools.score_m5 import evaluate as score_m5
    from tools.predict_m3 import generate as predict_m3
    from tools.predict_m5 import generate as predict_m5
    from paperbrain.graph import load_graph_policy
    from paperbrain.vector_store import self_test as vector_self_test

    tests = _unit_tests() if run_tests else {"result": "NOT_RUN", "reason": "library call"}
    m3_score = _score_generated(m3_golden, "M3", predict_m3, score_m3)
    policy = load_graph_policy()
    vss = vector_self_test()
    m3_ok = (m3_score.get("result") == "PASS" and policy.get("valid") is True and
             policy.get("review_due") is False and vss.get("ok") is True)
    gates = {
        "M1": _score_m1_current(m1_golden, score_m1),
        "M2": _m2(),
        "M3": {"result": "PASS" if m3_ok else "FAIL", "score": m3_score,
               "policy": {k: v for k, v in policy.items()
                          if k not in {"aliases", "blacklist"}},
               "vector_index": vss},
        "M4": _m4(thresholds or str(ROOT / "thresholds.json"), tests),
        "M5": _score_generated(m5_golden, "M5", predict_m5, score_m5),
        "M6": _m6(m6_report),
        "M7": _m7(),
        "M8": _m8(output_quality_report),
    }
    passed = [name for name, gate in gates.items() if gate.get("result") == "PASS"]
    failed = [name for name, gate in gates.items() if gate.get("result") != "PASS"]
    ignored = [name for name, value in (("M1", m1_pred), ("M3", m3_pred),
                                         ("M5", m5_pred)) if value]
    return {"schema": "paperbrain-release-v5.0", "result": "PASS" if not failed else "FAIL",
            "passed": passed, "failed": failed,
            "ignored_external_prediction_inputs": ignored, "gates": gates}


def main() -> int:
    ap = argparse.ArgumentParser()
    for gate in ("m1", "m3", "m5"):
        ap.add_argument(f"--{gate}-golden")
        ap.add_argument(f"--{gate}-pred",
                        help="兼容保留；统一发布门禁现场重生成预测，此参数不会参与放行")
    ap.add_argument("--m6-report")
    ap.add_argument("--output-quality-report")
    ap.add_argument("--thresholds", default=str(ROOT / "thresholds.json"))
    args = ap.parse_args()
    result = evaluate_release(m1_golden=args.m1_golden, m1_pred=args.m1_pred,
                              m3_golden=args.m3_golden, m3_pred=args.m3_pred,
                              m5_golden=args.m5_golden, m5_pred=args.m5_pred,
                              m6_report=args.m6_report,
                              output_quality_report=args.output_quality_report,
                              thresholds=args.thresholds,
                              run_tests=True)
    print(json.dumps(result, ensure_ascii=False, indent=2, default=list))
    return 0 if result["result"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
